/************************************************************************/
/*   R E F A L - 6         Copyright (C) 1992 by Arkady Klimov          */
/*      !!! This module was generated by GENTAB                         */
/*       rfelst.c    - list of built-in functions                       */
/************************************************************************/

#define LOGICAL int

char * blttxt[] = {
   /*  0 */  "APPLY",
   /*  1 */  "FREE",
   /*  2 */  "OPEN_FILE",
   /*  3 */  "ERASE_FILE",
   /*  4 */  "CLOSE_CHANNEL",
   /*  5 */  "PRINT!",
   /*  6 */  "PRINTLN!",
   /*  7 */  "READ!",
   /*  8 */  "READLN!",
   /*  9 */  "INPEXP",
   /* 10 */  "READ_CHAR!",
   /* 11 */  "READ_LINE!",
   /* 12 */  "READ_BLOCK!",
   /* 13 */  "WRITE!",
   /* 14 */  "WRITELN!",
   /* 15 */  "EOF",
   /* 16 */  "COMPARE",
   /* 17 */  "ADD",
   /* 18 */  "+",
   /* 19 */  "SUB",
   /* 20 */  "-",
   /* 21 */  "MUL",
   /* 22 */  "*",
   /* 23 */  "DIV",
   /* 24 */  "/",
   /* 25 */  "MOD",
   /* 26 */  "%",
   /* 27 */  "DIVMOD",
   /* 28 */  "\\",
   /* 29 */  "GCDSTEP",
   /* 30 */  "AND",
   /* 31 */  "&",
   /* 32 */  "XOR",
   /* 33 */  "^",
   /* 34 */  "OR",
   /* 35 */  "|",
   /* 36 */  "SHORT_INT",
   /* 37 */  "INT",
   /* 38 */  "SHORT_REAL",
   /* 39 */  "REAL",
   /* 40 */  "FUNC",
   /* 41 */  "ABS",
   /* 42 */  "SIGN",
   /* 43 */  "SQRT",
   /* 44 */  "EXP",
   /* 45 */  "LOG",
   /* 46 */  "SIN",
   /* 47 */  "ASIN",
   /* 48 */  "SINH",
   /* 49 */  "COS",
   /* 50 */  "ACOS",
   /* 51 */  "COSH",
   /* 52 */  "TAN",
   /* 53 */  "ATAN",
   /* 54 */  "TANH",
   /* 55 */  "TIME",
   /* 56 */  "TIME_ELAPSED",
   /* 57 */  "WTR",
   /* 58 */  "GTR",
   /* 59 */  "CPR",
   /* 60 */  "GETV",
   /* 61 */  "SETV",
   /* 62 */  "GETN",
   /* 63 */  "SETN",
   /* 64 */  "GETS",
   /* 65 */  "SETS",
   /* 66 */  "POS",
   /* 67 */  "SHIFT",
   /* 68 */  "CONCAT",
   /* 69 */  "LENCONT",
   /* 70 */  "NEW",
   /* 71 */  "GET",
   /* 72 */  "SET",
   /* 73 */  "MODE",
   /* 74 */  "CONST",
   /* 75 */  "MAKE",
   /* 76 */  "MOVE",
   /* 77 */  "COPY",
   /* 78 */  "SEND",
   /* 79 */  "REFCOUNT",
   /* 80 */  "MK_TABLE",
   /* 81 */  "TABLE_VALUE",
   /* 82 */  "TABLE_NAME",
   /* 83 */  "TABLE_LIST",
   /* 84 */  "TABLE_LINK",
   /* 85 */  "EXPLODE",
   /* 86 */  "IMPLODE",
   /* 87 */  "FIRST",
   /* 88 */  "LAST",
   /* 89 */  "LENGTH",
   /* 90 */  "LENW",
   /* 91 */  "TYPE",
   /* 92 */  "TYPE6",
   /* 93 */  "CHR",
   /* 94 */  "ORD",
   /* 95 */  "LOWER",
   /* 96 */  "UPPER",
   /* 97 */  "SYMB",
   /* 98 */  "NUMB",
   /* 99 */  "EXIT",
   /*100 */  "EXITCD",
   /*101 */  "STEP",
   /*102 */  "ARG",
   /*103 */  "TO_CHARS",
   /*104 */  "ENCODE",
   /*105 */  "DECODE",
   /*106 */  "GETENV",
   /*107 */  "TESTMEM",
   /*108 */  "BREAK",
   /*109 */  "INITGRAPH",
   /*110 */  "CLOSEGRAPH",
   /*111 */  "MOUSE"
};
int bltcnt = sizeof(blttxt)/sizeof(char *);

extern LOGICAL rb_apply();
extern LOGICAL rb_close_chan();
extern LOGICAL rb_open_file();
extern LOGICAL rb_erase_file();
extern LOGICAL rb_close_chan();
extern LOGICAL rb_print();
extern LOGICAL rb_println();
extern LOGICAL rb_read();
extern LOGICAL rb_readln();
extern LOGICAL rb_readln();
extern LOGICAL rb_read_char();
extern LOGICAL rb_read_line();
extern LOGICAL rb_read_block();
extern LOGICAL rb_write();
extern LOGICAL rb_writeln();
extern LOGICAL rb_eof();
extern LOGICAL rb_compare();
extern LOGICAL rb_add();
extern LOGICAL rb_add();
extern LOGICAL rb_sub();
extern LOGICAL rb_sub();
extern LOGICAL rb_mul();
extern LOGICAL rb_mul();
extern LOGICAL rb_div();
extern LOGICAL rb_div();
extern LOGICAL rb_mod();
extern LOGICAL rb_mod();
extern LOGICAL rb_divmod();
extern LOGICAL rb_divmod();
extern LOGICAL rb_gcdstep();
extern LOGICAL rb_and();
extern LOGICAL rb_and();
extern LOGICAL rb_xor();
extern LOGICAL rb_xor();
extern LOGICAL rb_or();
extern LOGICAL rb_or();
extern LOGICAL rb_short_int();
extern LOGICAL rb_int();
extern LOGICAL rb_short_real();
extern LOGICAL rb_real();
extern LOGICAL rb_func();
extern LOGICAL rb_abs();
extern LOGICAL rb_sign();
extern LOGICAL rb_sqrt();
extern LOGICAL rb_exp();
extern LOGICAL rb_log();
extern LOGICAL rb_sin();
extern LOGICAL rb_asin();
extern LOGICAL rb_sinh();
extern LOGICAL rb_cos();
extern LOGICAL rb_acos();
extern LOGICAL rb_cosh();
extern LOGICAL rb_tan();
extern LOGICAL rb_atan();
extern LOGICAL rb_tanh();
extern LOGICAL rb_time();
extern LOGICAL rb_time_elapsed();
extern LOGICAL rb_wtr();
extern LOGICAL rb_gtr();
extern LOGICAL rb_getv();
extern LOGICAL rb_getv();
extern LOGICAL rb_setv();
extern LOGICAL rb_getn();
extern LOGICAL rb_setn();
extern LOGICAL rb_gets();
extern LOGICAL rb_sets();
extern LOGICAL rb_pos();
extern LOGICAL rb_shift();
extern LOGICAL rb_concat();
extern LOGICAL rb_lencont();
extern LOGICAL rb_new();
extern LOGICAL rb_get();
extern LOGICAL rb_set();
extern LOGICAL rb_mode();
extern LOGICAL rb_const();
extern LOGICAL rb_make();
extern LOGICAL rb_move();
extern LOGICAL rb_copy();
extern LOGICAL rb_send();
extern LOGICAL rb_refcount();
extern LOGICAL rb_mk_table();
extern LOGICAL rb_tbl_value();
extern LOGICAL rb_tbl_name();
extern LOGICAL rb_tbl_list();
extern LOGICAL rb_tbl_link();
extern LOGICAL rb_to_chars();
extern LOGICAL rb_impl();
extern LOGICAL rb_first();
extern LOGICAL rb_last();
extern LOGICAL rb_length();
extern LOGICAL rb_lenw();
extern LOGICAL rb_type();
extern LOGICAL rb_type();
extern LOGICAL rb_chr();
extern LOGICAL rb_ord();
extern LOGICAL rb_lower();
extern LOGICAL rb_upper();
extern LOGICAL rb_to_chars();
extern LOGICAL rb_numb();
extern LOGICAL rb_exit();
extern LOGICAL rb_exitcd();
extern LOGICAL rb_step();
extern LOGICAL rb_arg();
extern LOGICAL rb_to_chars();
extern LOGICAL rb_encode();
extern LOGICAL rb_decode();
extern LOGICAL rb_getenv();
extern LOGICAL rb_testmem();
extern LOGICAL rb_break();
extern LOGICAL rb_initgraph();
extern LOGICAL rb_closegraph();
extern LOGICAL rb_mouse();

LOGICAL (* rf_subr[])() = {
        rb_apply,
        rb_close_chan,
        rb_open_file,
        rb_erase_file,
        rb_close_chan,
        rb_print,
        rb_println,
        rb_read,
        rb_readln,
        rb_readln,
        rb_read_char,
        rb_read_line,
        rb_read_block,
        rb_write,
        rb_writeln,
        rb_eof,
        rb_compare,
        rb_add,
        rb_add,
        rb_sub,
        rb_sub,
        rb_mul,
        rb_mul,
        rb_div,
        rb_div,
        rb_mod,
        rb_mod,
        rb_divmod,
        rb_divmod,
        rb_gcdstep,
        rb_and,
        rb_and,
        rb_xor,
        rb_xor,
        rb_or,
        rb_or,
        rb_short_int,
        rb_int,
        rb_short_real,
        rb_real,
        rb_func,
        rb_abs,
        rb_sign,
        rb_sqrt,
        rb_exp,
        rb_log,
        rb_sin,
        rb_asin,
        rb_sinh,
        rb_cos,
        rb_acos,
        rb_cosh,
        rb_tan,
        rb_atan,
        rb_tanh,
        rb_time,
        rb_time_elapsed,
        rb_wtr,
        rb_gtr,
        rb_getv,
        rb_getv,
        rb_setv,
        rb_getn,
        rb_setn,
        rb_gets,
        rb_sets,
        rb_pos,
        rb_shift,
        rb_concat,
        rb_lencont,
        rb_new,
        rb_get,
        rb_set,
        rb_mode,
        rb_const,
        rb_make,
        rb_move,
        rb_copy,
        rb_send,
        rb_refcount,
        rb_mk_table,
        rb_tbl_value,
        rb_tbl_name,
        rb_tbl_list,
        rb_tbl_link,
        rb_to_chars,
        rb_impl,
        rb_first,
        rb_last,
        rb_length,
        rb_lenw,
        rb_type,
        rb_type,
        rb_chr,
        rb_ord,
        rb_lower,
        rb_upper,
        rb_to_chars,
        rb_numb,
        rb_exit,
        rb_exitcd,
        rb_step,
        rb_arg,
        rb_to_chars,
        rb_encode,
        rb_decode,
        rb_getenv,
        rb_testmem,
        rb_break,
        rb_initgraph,
        rb_closegraph,
        rb_mouse
};
